# Generated by Django 4.2.18 on 2025-01-20 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0008_chartdata'),
    ]

    operations = [
        migrations.CreateModel(
            name='mirrorx2',
            fields=[
                ('date', models.DateTimeField()),
                ('symbol', models.CharField(max_length=100)),
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('orderId', models.BigIntegerField()),
                ('side', models.CharField(max_length=20)),
                ('price', models.FloatField()),
                ('qty', models.FloatField()),
                ('realizedPnl', models.FloatField()),
                ('marginAsset', models.CharField(max_length=20)),
                ('quoteQty', models.FloatField()),
                ('commission', models.FloatField()),
                ('commissionAsset', models.CharField(max_length=20)),
                ('time', models.BigIntegerField()),
                ('positionSide', models.CharField(max_length=20)),
                ('buyer', models.CharField(max_length=20)),
                ('maker', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'mirrorx2',
            },
        ),
        migrations.CreateModel(
            name='mirrorx3',
            fields=[
                ('date', models.DateTimeField()),
                ('symbol', models.CharField(max_length=100)),
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('orderId', models.BigIntegerField()),
                ('side', models.CharField(max_length=20)),
                ('price', models.FloatField()),
                ('qty', models.FloatField()),
                ('realizedPnl', models.FloatField()),
                ('marginAsset', models.CharField(max_length=20)),
                ('quoteQty', models.FloatField()),
                ('commission', models.FloatField()),
                ('commissionAsset', models.CharField(max_length=20)),
                ('time', models.BigIntegerField()),
                ('positionSide', models.CharField(max_length=20)),
                ('buyer', models.CharField(max_length=20)),
                ('maker', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'mirrorx3',
            },
        ),
        migrations.CreateModel(
            name='mirrorx4',
            fields=[
                ('date', models.DateTimeField()),
                ('symbol', models.CharField(max_length=100)),
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('orderId', models.BigIntegerField()),
                ('side', models.CharField(max_length=20)),
                ('price', models.FloatField()),
                ('qty', models.FloatField()),
                ('realizedPnl', models.FloatField()),
                ('marginAsset', models.CharField(max_length=20)),
                ('quoteQty', models.FloatField()),
                ('commission', models.FloatField()),
                ('commissionAsset', models.CharField(max_length=20)),
                ('time', models.BigIntegerField()),
                ('positionSide', models.CharField(max_length=20)),
                ('buyer', models.CharField(max_length=20)),
                ('maker', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'mirrorx4',
            },
        ),
        migrations.CreateModel(
            name='mirrorx5',
            fields=[
                ('date', models.DateTimeField()),
                ('symbol', models.CharField(max_length=100)),
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('orderId', models.BigIntegerField()),
                ('side', models.CharField(max_length=20)),
                ('price', models.FloatField()),
                ('qty', models.FloatField()),
                ('realizedPnl', models.FloatField()),
                ('marginAsset', models.CharField(max_length=20)),
                ('quoteQty', models.FloatField()),
                ('commission', models.FloatField()),
                ('commissionAsset', models.CharField(max_length=20)),
                ('time', models.BigIntegerField()),
                ('positionSide', models.CharField(max_length=20)),
                ('buyer', models.CharField(max_length=20)),
                ('maker', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'mirrorx5',
            },
        ),
        migrations.CreateModel(
            name='mirrorxfund',
            fields=[
                ('date', models.DateTimeField()),
                ('symbol', models.CharField(max_length=100)),
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('orderId', models.BigIntegerField()),
                ('side', models.CharField(max_length=20)),
                ('price', models.FloatField()),
                ('qty', models.FloatField()),
                ('realizedPnl', models.FloatField()),
                ('marginAsset', models.CharField(max_length=20)),
                ('quoteQty', models.FloatField()),
                ('commission', models.FloatField()),
                ('commissionAsset', models.CharField(max_length=20)),
                ('time', models.BigIntegerField()),
                ('positionSide', models.CharField(max_length=20)),
                ('buyer', models.CharField(max_length=20)),
                ('maker', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'mirrorxfund',
            },
        ),
        migrations.CreateModel(
            name='team',
            fields=[
                ('date', models.DateTimeField()),
                ('symbol', models.CharField(max_length=100)),
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('orderId', models.BigIntegerField()),
                ('side', models.CharField(max_length=20)),
                ('price', models.FloatField()),
                ('qty', models.FloatField()),
                ('realizedPnl', models.FloatField()),
                ('marginAsset', models.CharField(max_length=20)),
                ('quoteQty', models.FloatField()),
                ('commission', models.FloatField()),
                ('commissionAsset', models.CharField(max_length=20)),
                ('time', models.BigIntegerField()),
                ('positionSide', models.CharField(max_length=20)),
                ('buyer', models.CharField(max_length=20)),
                ('maker', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'team',
            },
        ),
        migrations.RenameModel(
            old_name='Trades',
            new_name='mirrorx1',
        ),
        migrations.AlterModelTable(
            name='chartdata',
            table='chart',
        ),
        migrations.AlterModelTable(
            name='mirrorx1',
            table='mirrorx1',
        ),
    ]
