# Generated by Django 5.0.1 on 2024-01-17 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_strategy'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trades',
            fields=[

                ('date',models.DateTimeField()),
                ('symbol', models.CharField(max_length=100)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('orderId', models.IntegerField()),
                ('side', models.CharField(max_length=20)),
                ('price', models.FloatField()),
                ('qty', models.FloatField()),
                ('realizedPnl', models.FloatField()),
                ('marginAsset', models.CharField(max_length=20)),
                ('quoteQty', models.FloatField()),
                ('commission', models.FloatField()),
                ('commissionAsset', models.CharField(max_length=20)),
                ('time', models.BigIntegerField()),
                ('positionSide', models.CharField(max_length=20)),
                ('buyer', models.IntegerField()),
                ('maker', models.IntegerField()),
            ],
            options={
                'db_table': 'mirrorx1 mirrorx2 mirrorx3 mirrorx4 mirrorx5 mirrorxfund',
            },
        ),
    ]
