# Generated by Django 5.0.1 on 2024-01-18 21:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('afdashboard', '0004_trades'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Strategy',
            new_name='Strategies',
        ),
    ]
