# Generated by Django 5.0.1 on 2024-01-21 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('afdashboard', '0005_rename_strategy_strategies'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trades',
            name='id',
            field=models.BigIntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='trades',
            name='orderId',
            field=models.BigIntegerField(),
        ),
    ]
