# Generated by Django 5.0.1 on 2024-01-21 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('afdashboard', '0006_alter_trades_id_alter_trades_orderid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trades',
            name='buyer',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='trades',
            name='maker',
            field=models.CharField(max_length=20),
        ),
    ]
