# Generated by Django 4.2.18 on 2025-01-21 16:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('afdashboard', '0009_mirrorx2_mirrorx3_mirrorx4_mirrorx5_mirrorxfund_team_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='team',
        ),
    ]
